export const componentInventory = [
  ['基础', 'aspect-ratio', '比例容器', ['card']],
  ['基础', 'avatar', '用户头像', ['badge', 'item']],
  ['基础', 'badge', '状态徽记', ['avatar', 'marker']],
  ['基础', 'bubble', '对话气泡', ['avatar', 'tooltip']],
  ['基础', 'card', '内容卡片', ['aspect-ratio', 'item']],
  ['基础', 'direction', '方向容器', ['typography']],
  ['基础', 'empty', '空白状态', ['button', 'item']],
  ['基础', 'item', '信息条目', ['avatar', 'card']],
  ['基础', 'kbd', '键盘快捷键', ['button', 'tooltip']],
  ['基础', 'marker', '内容标注', ['badge', 'separator']],
  ['基础', 'separator', '内容分隔线', ['item', 'marker']],
  ['基础', 'skeleton', '加载占位', ['card', 'item']],
  ['基础', 'typography', '文本排版', ['card', 'direction']],
  ['表单', 'attachment', '文件附件', []],
  ['表单', 'button', '操作按钮', ['button-group', 'toggle']],
  ['表单', 'button-group', '按钮编组', ['button', 'toggle-group']],
  ['表单', 'checkbox', '多选框', []],
  ['表单', 'combobox', '可搜索选择', ['select']],
  ['表单', 'field', '表单字段', ['input', 'label']],
  ['表单', 'input', '单行输入', ['input-group', 'label']],
  ['表单', 'input-group', '输入组合', ['input']],
  ['表单', 'input-otp', '验证码输入', ['input']],
  ['表单', 'label', '字段说明标签', ['input']],
  ['表单', 'radio-group', '单项选择', []],
  ['表单', 'select', '下拉选择', ['combobox']],
  ['表单', 'slider', '范围滑杆', []],
  ['表单', 'switch', '状态开关', []],
  ['表单', 'textarea', '多行输入', ['input']],
  ['表单', 'toggle', '切换控件', ['button']],
  ['表单', 'toggle-group', '切换控件组', ['button-group', 'toggle']],
  ['导航', 'calendar', '日期日历', ['date-picker']],
  ['导航', 'date-picker', '单日选择', ['calendar', 'date-range-picker']],
  ['导航', 'date-range-picker', '日期区间', ['calendar', 'date-picker']],
  ['导航', 'accordion', '折叠内容', ['collapsible']],
  ['导航', 'breadcrumb', '路径导航', []],
  ['导航', 'collapsible', '展开收起', ['accordion']],
  ['导航', 'menubar', '应用菜单', ['navigation-menu']],
  ['导航', 'navigation-menu', '站点导航', ['menubar']],
  ['导航', 'pagination', '页码导航', []],
  ['导航', 'tabs', '选项卡', []],
  ['浮层', 'alert', '通知提示', ['alert-dialog']],
  ['浮层', 'alert-dialog', '确认对话', ['dialog', 'alert']],
  ['浮层', 'command', '命令调度', []],
  ['浮层', 'context-menu', '上下文菜单', ['dropdown-menu']],
  ['浮层', 'dialog', '模态窗口', ['alert-dialog', 'drawer']],
  ['浮层', 'drawer', '抽屉面板', ['dialog', 'sheet']],
  ['浮层', 'dropdown-menu', '下拉菜单', ['context-menu']],
  ['浮层', 'hover-card', '悬浮信息卡', ['tooltip']],
  ['浮层', 'popover', '弹出卡片', ['hover-card', 'tooltip']],
  ['浮层', 'sheet', '侧边面板', ['drawer']],
  ['浮层', 'tooltip', '悬停提示', ['hover-card']],
  ['数据与反馈', 'carousel', '内容轮播', []],
  ['数据与反馈', 'chart', '数据图形', []],
  ['数据与反馈', 'message', '会话消息', ['sonner']],
  ['数据与反馈', 'message-scroller', '消息滚动区', ['message']],
  ['数据与反馈', 'progress', '完成进度', []],
  ['数据与反馈', 'resizable', '可调尺寸', []],
  ['数据与反馈', 'scroll-area', '滚动区域', []],
  ['数据与反馈', 'sonner', '轻量通知', ['message']],
  ['数据与反馈', 'spinner', '忙碌动画', []],
  ['数据与反馈', 'table', '数据表格', []]
] as const

export const baseSlugs = [
  'aspect-ratio',
  'avatar',
  'badge',
  'bubble',
  'card',
  'direction',
  'empty',
  'item',
  'kbd',
  'marker',
  'separator',
  'skeleton',
  'typography'
] as const

export const componentSlugs = componentInventory.map(([, slug]) => slug)

export const guideInventory = [
  { path: '/docs/getting-started', title: '开始使用', summary: '了解 MoriUI 的组合方式与文档路径。', toc: ['适用场景', '基本组成', '下一步'] },
  { path: '/docs/installation', title: '安装', summary: '安装包、接入样式并渲染第一个组件。', toc: ['安装依赖', '引入样式', '第一个组件'] },
  { path: '/docs/themes', title: '主题', summary: '通过 html[data-theme] 使用 Nova 的浅深模式。', toc: ['主题入口', '切换模式', '保持一致'] },
  { path: '/docs/releases', title: '发布说明', summary: '理解版本节奏并安全升级。', toc: ['版本策略', '升级前', '升级后'] },
  { path: '/docs/migration', title: '迁移', summary: '将现有 Vue 界面逐步迁移到 MoriUI。', toc: ['迁移顺序', '替换样式', '验证交互'] }
] as const
