export { default as ScrollArea } from './ScrollArea.vue'
export type { ScrollAreaOrientation } from './ScrollArea.vue'
export { default as ScrollAreaCorner } from './ScrollAreaCorner.vue'
export { default as ScrollAreaScrollbar } from './ScrollAreaScrollbar.vue'
export { default as ScrollAreaThumb } from './ScrollAreaThumb.vue'
export { default as ScrollAreaViewport } from './ScrollAreaViewport.vue'
export { scrollAreaVariants } from './variants'
export type { ScrollAreaVariants } from './variants'
